# Generated by Django 3.0.7 on 2020-06-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectpicture', models.ImageField(upload_to='ErrorPic')),
                ('projectname', models.CharField(max_length=50, verbose_name='Name')),
                ('projectfile', models.FileField(null=True, upload_to='SolverFile')),
            ],
        ),
        migrations.AlterField(
            model_name='errorsolver',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='errorsolver',
            name='solverfile',
            field=models.FileField(null=True, upload_to='SolverFile'),
        ),
    ]
