# Generated by Django 3.0.7 on 2020-06-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200623_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='projectfile',
            field=models.FileField(null=True, upload_to='ProFile'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projectpicture',
            field=models.ImageField(upload_to='ProPic'),
        ),
    ]
