# Generated by Django 3.0.7 on 2020-07-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200719_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='errorname',
            new_name='Subtitle',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='name',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='application',
            name='solverfile',
        ),
        migrations.AddField(
            model_name='application',
            name='Application',
            field=models.FileField(null=True, upload_to='Application'),
        ),
        migrations.AddField(
            model_name='application',
            name='PythonFile',
            field=models.FileField(null=True, upload_to='Python'),
        ),
    ]
