# Generated by Django 3.0.7 on 2020-07-19 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200719_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='Subtitle',
            new_name='Description',
        ),
    ]
