# Generated by Django 3.0.7 on 2020-07-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200719_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hacking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName', models.CharField(max_length=50, verbose_name='Name')),
                ('Working', models.TextField(blank=True)),
                ('File', models.FileField(null=True, upload_to='ProFile')),
            ],
        ),
        migrations.RenameField(
            model_name='django_project',
            old_name='projectfile',
            new_name='ProjectFile',
        ),
        migrations.RenameField(
            model_name='django_project',
            old_name='projectname',
            new_name='ProjectName',
        ),
        migrations.AddField(
            model_name='django_project',
            name='Description',
            field=models.TextField(blank=True),
        ),
    ]
