# Generated by Django 3.0.7 on 2020-07-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200723_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='django_project',
            old_name='ProjectFile',
            new_name='ProjectFolder',
        ),
    ]
