# Generated by Django 3.0.7 on 2020-07-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_fruit_person_runner_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
        migrations.DeleteModel(
            name='Fruit',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Runner',
        ),
        migrations.DeleteModel(
            name='test',
        ),
        migrations.RemoveField(
            model_name='application',
            name='id',
        ),
        migrations.RemoveField(
            model_name='django_project',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hacking',
            name='id',
        ),
        migrations.AlterField(
            model_name='application',
            name='Title',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='django_project',
            name='ProjectName',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='hacking',
            name='FileName',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Name'),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
