# Generated by Django 3.0.7 on 2020-07-24 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200724_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='Application',
            new_name='ExeFile',
        ),
    ]
